#kubectl exec deploy/ftps -- pkill vsftpd OK
#kubectl exec deploy/nginx -- pkill nginx OK
#kubectl exec deploy/mysql -- pkill mysqld OK
#kubectl exec deploy/grafana -- pkill grafana-server OK
#kubectl exec deploy/telegraf -- pkill telegraf OK
#kubectl exec deploy/influxdb -- pkill influxd OK
#kubectl exec deploy/phpmyadmin -- pkill nginx OK
#kubectl exec deploy/wordpress -- pkill nginx OK
#kubectl exec deploy/nginx -- pkill sshd OK
#kubectl exec deploy/phpmyadmin -- pkill php OK
#kubectl exec deploy/wordpress -- pkill php OK