apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  ports:
    - name: wp-port
      protocol: TCP
      port: 5050
      targetPort: 80
  type: LoadBalancer
  #loadBalancerIP: 192.168.49.15
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress-img
        ports:
        - containerPort: 5050
        imagePullPolicy: Never
